-- MySQL Script generated by MySQL Workbench
-- Wed Feb 14 10:26:47 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `ID` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Contrasña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cafeterias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cafeterias` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NULL,
  `Calificacion` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Productos` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Precio` DECIMAL(9,2) NULL,
  `Promedio` DECIMAL(3,2) NULL,
  `Cafeterias_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Productos_Cafeterias1_idx` (`Cafeterias_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_Cafeterias1`
    FOREIGN KEY (`Cafeterias_ID`)
    REFERENCES `mydb`.`Cafeterias` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ReseñasProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ReseñasProducto` (
  `ID` INT NOT NULL,
  `Calificacion` VARCHAR(45) NULL,
  `Comentario` VARCHAR(45) NOT NULL,
  `ProductoID` INT NULL,
  `UsuarioID` INT NULL,
  `Usuario_ID` INT NOT NULL,
  `Productos_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_ReseñasProducto_Usuario1_idx` (`Usuario_ID` ASC) VISIBLE,
  INDEX `fk_ReseñasProducto_Productos1_idx` (`Productos_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ReseñasProducto_Usuario1`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `mydb`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ReseñasProducto_Productos1`
    FOREIGN KEY (`Productos_ID`)
    REFERENCES `mydb`.`Productos` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ReseñaCafeteria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ReseñaCafeteria` (
  `ID` INT NOT NULL,
  `Calificacion` DECIMAL(2,1) NOT NULL,
  `Comentario` TEXT NULL,
  `CafeteriaID` INT NULL,
  `UsuarioID` INT NULL,
  `Usuarios_ID` INT NOT NULL,
  `Cafeterias_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_ReseñaCafeteria_Usuarios1_idx` (`Usuarios_ID` ASC) VISIBLE,
  INDEX `fk_ReseñaCafeteria_Cafeterias1_idx` (`Cafeterias_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ReseñaCafeteria_Usuarios1`
    FOREIGN KEY (`Usuarios_ID`)
    REFERENCES `mydb`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ReseñaCafeteria_Cafeterias1`
    FOREIGN KEY (`Cafeterias_ID`)
    REFERENCES `mydb`.`Cafeterias` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Administradores` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NombreUsuarios` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `Usuario_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Administradores_Usuario1_idx` (`Usuario_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Administradores_Usuario1`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `mydb`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
$$

DELIMITER ;

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
